name: Selenium Download Automation

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'selenium_download.py'

jobs:
  selenium-download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        install-chromedriver: true
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r webhook_requirements.txt
    
    - name: Create result_files directory
      run: mkdir -p result_files
    
    - name: Run selenium download script
      run: |
        echo "Starting selenium download script..."
        echo "Python version: $(python --version)"
        echo "Chrome version: $(google-chrome --version)"
        echo "ChromeDriver version: $(chromedriver --version)"
        echo "Current directory: $(pwd)"
        echo "Files in directory: $(ls -la)"
        echo "Running script..."
        python selenium_download.py
        echo "Script completed with exit code: $?"
      env:
        CHROME_BIN: /usr/bin/google-chrome
        CHROMEDRIVER: /usr/bin/chromedriver
    
    - name: Update webhook results
      run: |
        echo "Updating webhook with latest results..."
        python update_webhook_results.py
    
    - name: Check for new files
      id: check_files
      run: |
        if [ -n "$(find result_files -name "*.csv" -newer selenium_download.py 2>/dev/null)" ]; then
          echo "new_files=true" >> $GITHUB_OUTPUT
        else
          echo "new_files=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push results
      if: steps.check_files.outputs.new_files == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add result_files/
        git add debug_screenshots/ || true
        git commit -m "Automated download: $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
        git push
